name: CI/CD - Deploy CloudFormation PoC

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: dev
        type: choice
        options:
          - dev

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install zip and wget
        run: sudo apt-get update && sudo apt-get install -y zip wget

      # ------------------ Build Lambda layer ------------------
      - name: Build Lambda layer (no numpy)
        run: |
          mkdir -p layer_build
          docker run --rm -v $PWD/layer_build:/var/task amazonlinux:2 /bin/bash -c "
            yum install -y python3.11 python3-pip zip gcc libffi-devel postgresql-devel
            python3.11 -m pip install --upgrade pip
            mkdir -p python
            pip3 install cryptography psycopg2-binary cffi pgvector -t python
            rm -rf python/numpy*
            zip -r ingest-dependencies-layer.zip python
            mv ingest-dependencies-layer.zip /var/task/
          "

      # ------------------ Publish Lambda layer ------------------
      - name: Publish Lambda layer
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name ingest-dependencies-layer \
            --description "Dependencies for PoC Lambda" \
            --zip-file fileb://layer_build/ingest-dependencies-layer.zip \
            --compatible-runtimes python3.11 \
            --region $AWS_REGION \
            --query 'LayerVersionArn' \
            --output text)
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      # ------------------ Prepare Lambda package ------------------
      - name: Prepare Lambda package
        run: |
          mkdir -p package
          cp lambda/*.py package/
          python -m pip install --upgrade pip
          pip install --target ./package -r lambda/requirements.txt --no-deps
          rm -rf package/numpy*
          rm -rf package/__pycache__/
          pushd package
          zip -r ../s3_handler.zip *
          popd

      # ------------------ Upload Lambda artifact ------------------
      - name: Upload Lambda artifact to S3
        run: |
          BUCKET_NAME=$(echo "${{ secrets.CFN_CODE_BUCKET }}" | sed -E 's#^arn:aws:s3:::(.+)$#\1#')
          aws s3 cp s3_handler.zip s3://$BUCKET_NAME/lambda/s3_handler.zip --region $AWS_REGION

      # ------------------ Deploy CloudFormation ------------------
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cft/template.yml \
            --stack-name bedrock-s3-ingest-poc \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              S3HandlerLambdaS3Bucket=${{ secrets.CFN_CODE_BUCKET }} \
              S3HandlerLambdaS3Key=lambda/s3_handler.zip \
              S3HandlerLambdaLayerArn=$LAYER_ARN \
              DBUsername=poc_admin \
              DBName=bedrock_poc \
            --region $AWS_REGION
