name: CI/CD - Deploy CloudFormation PoC

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: dev
        type: choice
        options:
          - dev

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip and wget
        run: sudo apt-get update && sudo apt-get install -y zip wget build-essential

      # ------------------ Build Lambda layer (Python 3.11 + numpy + other deps) ------------------
      - name: Build Lambda layer
        run: |
          mkdir -p layer_build
          docker run --rm -v $PWD/layer_build:/var/task amazonlinux:2 /bin/bash -c "
            set -e

            # Install build dependencies
            yum update -y
            yum groupinstall -y 'Development Tools'
            yum install -y gcc gcc-c++ make wget tar gzip zip \
                libffi-devel postgresql-devel bzip2 bzip2-devel xz-devel zlib-devel

            # Build Python 3.11 from source
            cd /tmp
            wget https://www.python.org/ftp/python/3.11.10/Python-3.11.10.tgz
            tar xvf Python-3.11.10.tgz
            cd Python-3.11.10
            ./configure --enable-optimizations --with-ensurepip=install
            make -j$(nproc)
            make altinstall   # installs python3.11

            python3.11 --version

            # Prepare Lambda layer folder
            mkdir -p /var/task/python

            # Install packages into layer folder
            python3.11 -m pip install --upgrade pip setuptools wheel
            python3.11 -m pip install numpy==1.26.4 cryptography psycopg2-binary cffi pgvector -t /var/task/python

            # Create zip
            cd /var/task
            zip -r ingest-dependencies-layer.zip python
            ls -lh ingest-dependencies-layer.zip
          "

      # ------------------ Publish Lambda layer ------------------
      - name: Publish Lambda layer
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name ingest-dependencies-layer \
            --description "Dependencies for all PoC Lambdas" \
            --zip-file fileb://layer_build/ingest-dependencies-layer.zip \
            --compatible-runtimes python3.11 \
            --region $AWS_REGION \
            --query 'LayerVersionArn' \
            --output text)
          echo "Layer ARN: $LAYER_ARN"
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      # ------------------ Prepare Lambda packages ------------------
      - name: Prepare Lambda packages
        run: |
          mkdir -p package

          # Copy all Python files from lambda/ to package/
          cp lambda/*.py package/

          # Install lightweight dependencies (excluding numpy)
          python -m pip install --upgrade pip
          pip install --target ./package -r lambda/requirements.txt --no-deps

          # Create zips for all Lambdas
          pushd package
          zip -r ../ingest.zip *
          zip -r ../knowledgebase_handler.zip *
          zip -r ../init_db.zip *
          popd

      # ------------------ Upload Lambda artifacts ------------------
      - name: Upload Lambda artifacts to S3
        run: |
          BUCKET_NAME=$(echo "${{ secrets.CFN_CODE_BUCKET }}" | sed -E 's#^arn:aws:s3:::(.+)$#\1#')
          aws s3 cp ingest.zip s3://$BUCKET_NAME/lambda/ingest.zip --region $AWS_REGION
          aws s3 cp knowledgebase_handler.zip s3://$BUCKET_NAME/lambda/knowledgebase_handler.zip --region $AWS_REGION
          aws s3 cp init_db.zip s3://$BUCKET_NAME/lambda/init_db.zip --region $AWS_REGION

      # ------------------ Deploy CloudFormation ------------------
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cft/template.yml \
            --stack-name bedrock-s3-ingest-poc \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              IngestLambdaS3Bucket=${{ secrets.CFN_CODE_BUCKET }} \
              IngestLambdaS3Key=lambda/ingest.zip \
              IngestLambdaLayerArn=$LAYER_ARN \
              KnowledgeBaseHandlerS3Bucket=${{ secrets.CFN_CODE_BUCKET }} \
              KnowledgeBaseHandlerS3Key=lambda/knowledgebase_handler.zip \
              KnowledgeBaseHandlerLayerArn=$LAYER_ARN \
              InitDBLambdaS3Bucket=${{ secrets.CFN_CODE_BUCKET }} \
              InitDBLambdaS3Key=lambda/init_db.zip \
              InitDBLambdaLayerArn=$LAYER_ARN \
              DBUsername=poc_admin \
              DBName=bedrock_poc \
            --region $AWS_REGION
